package com.example.alvar.chatapp.Activities;

import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.design.widget.CoordinatorLayout;
import android.support.design.widget.TextInputLayout;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.widget.Button;
import android.widget.ProgressBar;
import android.widget.Toast;

import com.example.alvar.chatapp.R;
import com.example.alvar.chatapp.Utils.ProgressBarHelper;
import com.example.alvar.chatapp.Utils.SnackbarHelper;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;

public class RecoverPasswordActivity extends AppCompatActivity {

    private static final String TAG = "RecoverPasswordActivity";

    //firebase
    private FirebaseAuth mAuth;

    //ui elements
    private TextInputLayout recoverPassword;
    private Button recoverPasswordBtn;
    private Toolbar toolbarRecovery;
    private ProgressBar progressBar;
    private CoordinatorLayout coordinatorLayout;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recover_password);
        bindUI();
        //init firebase auth
        mAuth = FirebaseAuth.getInstance();
        //init toolbar
        setToolbar(getString(R.string.toolbarRecoveryPasswordTitle));

        recoverPasswordBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //show progressBar
                ProgressBarHelper.showProgressBar(progressBar);
                //execute email recovery method
                sendEmailrecovery();
            }
        });
    }

    private void bindUI(){
        recoverPassword = findViewById(R.id.recoverPassword);
        recoverPasswordBtn = findViewById(R.id.recoverPasswordBtn);
        toolbarRecovery = findViewById(R.id.toolbarRecovery);
        progressBar = findViewById(R.id.recoveryProgressBar);
        coordinatorLayout = findViewById(R.id.coordinatorLayout);
    }

    private void setToolbar(String title){
        //create toolbar
        toolbarRecovery = findViewById(R.id.toolbarRecovery);
        //we set the toolbar
        setSupportActionBar(toolbarRecovery);
        //we pass the title
        getSupportActionBar().setTitle(title);
        //enable back button
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    }

    /**
     * method in charge of sending to the user an email to recover password
     */
    private void sendEmailrecovery() {
        //we capture email enter by user
        String emailtext = recoverPassword.getEditText().getText().toString();

        if (emailtext.equals("")) {
            //show message to the user
            SnackbarHelper.showSnackBarLong(coordinatorLayout, getString(R.string.enterEmailForRecovery));
            //hide progressbar
            ProgressBarHelper.hideProgressBar(progressBar);
        } else{
            mAuth.sendPasswordResetEmail(emailtext).addOnCompleteListener(new OnCompleteListener<Void>() {
                @Override
                public void onComplete(@NonNull Task<Void> task) {
                    if (task.isSuccessful()){
                        //show confirmation message to the user
                        Toast.makeText(RecoverPasswordActivity.this, getString(R.string.recoverPassword), Toast.LENGTH_SHORT).show();
                        //finish
                        finish();
                    } else {
                        //we save the exception message generated by firebase
                        String error = task.getException().getMessage();
                        //show error to the user
                        Toast.makeText(RecoverPasswordActivity.this, error, Toast.LENGTH_LONG).show();
                        //hide progressbar
                        ProgressBarHelper.hideProgressBar(progressBar);
                    }
                }
            });
        }
    }
}
